name "ckan"
description "Installs and configures CKAN."
version "0.1.0"
maintainer "Brook Elgie"
maintainer_email "brook.elgie@okfn.org"
license "AGPL"
recipe "ckan", "Includes the ckan_base and ckan_datastore recipes to install and configure a ckan instance with datastore extension ready for development."
recipe "ckan::ckan_base", "Installs ckan and dependencies."
recipe "ckan::ckan_datastore", "Installs the Datastore extension."
recipe "ckan::ckan_production", "Installs dependencies used for a production instance of ckan."
recipe "ckan::ckan_tests", "Runs ckan tests."

depends "git"
depends "python"
depends "postgresql"
depends "java"
depends "nodejs"
