name "ckan"
description "Installs and configures CKAN."
version "0.1.0"
maintainer "Brook Elgie"
maintainer_email "brook.elgie@okfn.org"
license "AGPL"
depends "git"
depends "python"
depends "postgresql"
depends "java"
